name = lingua
title = Lingua
description = Create your own languages, encode messages, and share dictionaries
depends = default
supported_games = minetest_game, lean_core
license = GPL-3.0-only
